# Generated by Django 4.1.1 on 2022-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.IntegerField()),
                ('customer', models.CharField(max_length=30)),
                ('staff', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
