# Generated by Django 4.1.1 on 2022-10-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0002_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt_id',
        ),
    ]
