# Generated by Django 4.1.1 on 2022-10-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0003_remove_transaction_receipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='transaction_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_sales', models.IntegerField()),
                ('transaction_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_login.transaction')),
            ],
        ),
    ]
