# Generated by Django 4.1.1 on 2022-10-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0004_transaction_contact_number_transaction_products'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction_products',
            table='transaction_products',
        ),
    ]
