# Generated by Django 4.1.1 on 2022-10-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0005_alter_transaction_products_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_products',
            old_name='transaction_id',
            new_name='transaction',
        ),
    ]
