# Generated by Django 4.1.1 on 2022-10-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0006_rename_transaction_id_transaction_products_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
