# Generated by Django 4.1.1 on 2022-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0007_alter_transaction_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_products',
            name='t_date',
            field=models.DateField(null=True),
        ),
    ]
